export const BRAZILIAN_AIRPORTS: { [key: string]: string } = {
  'São Paulo': 'GRU',
  'Rio de Janeiro': 'GIG',
  'Brasília': 'BSB',
  'Salvador': 'SSA',
  'Fortaleza': 'FOR',
  'Recife': 'REC',
  'Porto Alegre': 'POA',
  'Manaus': 'MAO',
  'Belém': 'BEL',
  'Curitiba': 'CWB',
  'Florianópolis': 'FLN',
  'Natal': 'NAT',
  'Vitória': 'VIX',
  'Cuiabá': 'CGB',
  'Campo Grande': 'CGR',
  'João Pessoa': 'JPA',
  'Maceió': 'MCZ',
  'Goiânia': 'GYN',
};